servers:
- url: "https://api.cartesia.ai"
  x-fern-server-name: Production
paths:
  /tts/clip:
    post:
      x-fern-sdk-group-name: Streaming
      x-fern-sdk-method-name: clip
  /tts/sse:
    post:
      x-fern-sdk-group-name: Streaming
      x-fern-sdk-method-name: convert
      x-fern-streaming: true
      responses:
        "200":
          description: A stream of audio data.
          content:
            application/json:
              schema:
                oneOf:
                  - $ref: "#/components/schemas/JSONChunkResponse"
                  - $ref: "#/components/schemas/JSONDoneResponse"
                  - $ref: "#/components/schemas/JSONErrorResponse"      
  /:
    get:
      x-fern-ignore: true
  "":
    get:
      operationId: apiStatusAndVersion
      security: []
      summary: API Status and Version
      description: Returns the server's version and a status message which can be useful for sanity checking.
      responses:
        "200":
          description: Everything OK.
          content:
            application/json:
              schema:
                type: object
                properties:
                  version:
                    type: string
                    title: version
                  status:
                    type: boolean
                    title: ok
        default:
          $ref: "#/components/responses/Error"