openapi: 3.0.0
info:
  title: Cartesia Websocket API
  version: "1.0.0"

servers:
  - url: wss://api.cartesia.ai/
    description: Production WebSocket Server
    protocol: wss
    x-fern-server-name: Production

paths: {}
components: {}
